## Get nucleotide frequencies of Tuberculosis genome
Mycobacterium tuberculosis H37Rv

In [3]:
! wget "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=NC_000962.3&rettype=fasta&retmode=text" -O data/NC_000962.3.fasta

--2025-06-27 12:28:01--  https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=NC_000962.3&rettype=fasta&retmode=text
Resolving eutils.ncbi.nlm.nih.gov (eutils.ncbi.nlm.nih.gov)... 2607:f220:41e:4290::110, 130.14.29.110
Connecting to eutils.ncbi.nlm.nih.gov (eutils.ncbi.nlm.nih.gov)|2607:f220:41e:4290::110|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: ‘data/NC_000962.3.fasta’

data/NC_000962.3.fa     [    <=>             ]   4,27M  5,27MB/s    in 0,8s

2025-06-27 12:28:03 (5,27 MB/s) - ‘data/NC_000962.3.fasta’ saved [4474618]

In [58]:
from collections import Counter
import numpy as np
import pandas as pd
from Bio import SeqIO
import sys

In [12]:
def calculate_nucleotide_frequencies(fasta_path):
    """
    Calculates nucleotide fequencies of a genome.
    Would also work for a fasta file with more than one sequence, even though I'm using it for a whole genome fasta file.
    """
    total_counts = Counter()

    for record in SeqIO.parse(fasta_path, "fasta"):
        seq = str(record.seq).upper()
        total_counts.update(seq)

    total_nucleotides = sum(total_counts[nuc] for nuc in "ACGT")
    frequencies = {nuc: total_counts[nuc] / total_nucleotides for nuc in "ACGT"}

    print("Nucleotide Frequencies:")
    for nuc in "ACGT":
        print(f"{nuc}: {frequencies[nuc]:.4f}")
    return frequencies

freq = calculate_nucleotide_frequencies("data/NC_000962.3.fasta")

Nucleotide Frequencies:
A: 0.1719
C: 0.3287
G: 0.3275
T: 0.1719

In [17]:
def create_hky_q_matrix(frequencies, kappa):
    """
    Creates the scaled HKY Q matrix such that the expected substitution rate is 1.
    Rows and columns are ordered as A, C, G, T.
    """
    nucs = ['A', 'C', 'G', 'T']
    pi = [frequencies[nuc] for nuc in nucs]

    # Initialize Q matrix
    Q = np.zeros((4, 4))

    # Define transitions and transversions
    transitions = {('A', 'G'), ('G', 'A'), ('C', 'T'), ('T', 'C')}

    for i, ni in enumerate(nucs):
        for j, nj in enumerate(nucs):
            if i == j:
                continue
            if (ni, nj) in transitions:
                Q[i, j] = kappa * frequencies[nj]
            else:
                Q[i, j] = frequencies[nj]

    # Set diagonal entries so rows sum to zero
    for i in range(4):
        Q[i, i] = -np.sum(Q[i, :])

    # Scale so that the expected substitution rate is 1
    total_rate = -sum(pi[i] * Q[i, i] for i in range(4))
    Q /= total_rate

    return Q, pd.DataFrame(Q, index=nucs, columns=nucs)

In [23]:
Q, Q_df = create_hky_q_matrix(freq, kappa = 2.07)
Q

array([[-1.21861714,  0.3398901 ,  0.70096006,  0.17776698],
       [ 0.17781012, -0.88441582,  0.33862805,  0.36797766],
       [ 0.36806694,  0.3398901 , -0.88572402,  0.17776698],
       [ 0.17781012,  0.7035725 ,  0.33862805, -1.22001066]])

In [24]:
# scale Q by substitution rate
mu = 4.6e-8
Q = mu * Q
Q

array([[-5.60563883e-08,  1.56349444e-08,  3.22441626e-08,
         8.17728129e-09],
       [ 8.17926531e-09, -4.06831277e-08,  1.55768902e-08,
         1.69269723e-08],
       [ 1.69310792e-08,  1.56349444e-08, -4.07433049e-08,
         8.17728129e-09],
       [ 8.17926531e-09,  3.23643349e-08,  1.55768902e-08,
        -5.61204904e-08]])

Seq-Gen interprets branch lengths as units of expected substitutions per site. If a branch length is 0.1, Seq-Gen treats it as 0.1 expected substitutions per site.

Suppose: A branch length in your tree is 1.2 years. The substitution rate is μ=4.6×10−8 substitutions/site/year. To tell Seq-Gen: “this branch evolves for 1.2 years at this rate,” you compute: Substitutions/site on this branch=μ⋅time=4.6×10−8⋅1.2=5.52×10−8
→ This is the value that Seq-Gen needs as the branch length

In [6]:
2000 * np.exp(-200*0.02)

np.float64(36.631277777468355)

In [71]:
from Bio import Nexus, Phylo
from io import StringIO

In [51]:
treepath = "/Users/mariebecker/Documents/Uni/ETH/RotationStadler/BESP_paper-analyses/results/pop_size_simulations/linear_constant/uniform/uniform_0.tree"
tree = Phylo.read(treepath, "newick")
#Phylo.write(tree, "converted.nex", "nexus")

In [52]:
tree.get_terminals()

[Clade(branch_length=85.51169686, name='t123'),
 Clade(branch_length=85.20077156, name='t124'),
 Clade(branch_length=29.40221713, name='t125'),
 Clade(branch_length=29.20843118, name='t126'),
 Clade(branch_length=244.644568, name='t127'),
 Clade(branch_length=26.18635088, name='t128'),
 Clade(branch_length=26.14262086, name='t129'),
 Clade(branch_length=21.42206384, name='t130'),
 Clade(branch_length=19.96622763, name='t131'),
 Clade(branch_length=36.97792539, name='t132'),
 Clade(branch_length=24.31275061, name='t133'),
 Clade(branch_length=15.27725582, name='t134'),
 Clade(branch_length=14.6616526, name='t135'),
 Clade(branch_length=21.20150853, name='t136'),
 Clade(branch_length=43.9680417, name='t137'),
 Clade(branch_length=12.81287944, name='t138'),
 Clade(branch_length=11.90913365, name='t139'),
 Clade(branch_length=6.631340953, name='t140'),
 Clade(branch_length=6.186669348, name='t141'),
 Clade(branch_length=282.3984372, name='t142'),
 Clade(branch_length=24.8067227, name='t143'),
 Clade(branch_length=24.01293535, name='t144'),
 Clade(branch_length=1.665177037, name='t145'),
 Clade(branch_length=1.233016773, name='t146'),
 Clade(branch_length=5.075415489, name='t147'),
 Clade(branch_length=4.331392641, name='t148'),
 Clade(branch_length=9.287065444, name='t149'),
 Clade(branch_length=25.77983416, name='t150'),
 Clade(branch_length=23.14353761, name='t151'),
 Clade(branch_length=23.01059492, name='t152'),
 Clade(branch_length=39.32858169, name='t153'),
 Clade(branch_length=38.86890371, name='t154'),
 Clade(branch_length=6.501519402, name='t155'),
 Clade(branch_length=5.112483802, name='t156'),
 Clade(branch_length=4.798736082, name='t157'),
 Clade(branch_length=16.76180654, name='t158'),
 Clade(branch_length=11.51923451, name='t159'),
 Clade(branch_length=10.72834069, name='t160'),
 Clade(branch_length=50.77555151, name='t161'),
 Clade(branch_length=18.15745443, name='t162'),
 Clade(branch_length=17.95611744, name='t163'),
 Clade(branch_length=18.00394497, name='t164'),
 Clade(branch_length=6.370289088, name='t165'),
 Clade(branch_length=5.935099884, name='t166'),
 Clade(branch_length=20.07805183, name='t167'),
 Clade(branch_length=19.66252073, name='t168'),
 Clade(branch_length=50.2751031, name='t169'),
 Clade(branch_length=49.96946908, name='t170'),
 Clade(branch_length=20.7640469, name='t171'),
 Clade(branch_length=20.55289959, name='t172'),
 Clade(branch_length=3.132601653, name='t173'),
 Clade(branch_length=3.081646737, name='t174'),
 Clade(branch_length=10.60626825, name='t175'),
 Clade(branch_length=8.38900566, name='t176'),
 Clade(branch_length=8.221200168, name='t177'),
 Clade(branch_length=75.9061895, name='t178'),
 Clade(branch_length=12.93423768, name='t179'),
 Clade(branch_length=11.948838, name='t180'),
 Clade(branch_length=19.73975543, name='t181'),
 Clade(branch_length=18.66957601, name='t182'),
 Clade(branch_length=50.89858956, name='t183'),
 Clade(branch_length=19.70217632, name='t184'),
 Clade(branch_length=19.66577465, name='t185'),
 Clade(branch_length=10.86301823, name='t186'),
 Clade(branch_length=10.85438142, name='t187'),
 Clade(branch_length=20.13616126, name='t188'),
 Clade(branch_length=246.7057591, name='t189'),
 Clade(branch_length=35.5785022, name='t190'),
 Clade(branch_length=35.23160107, name='t191'),
 Clade(branch_length=24.6913429, name='t192'),
 Clade(branch_length=23.47929574, name='t193'),
 Clade(branch_length=97.06484683, name='t1'),
 Clade(branch_length=23.71789582, name='t2'),
 Clade(branch_length=23.66248825, name='t3'),
 Clade(branch_length=74.61738058, name='t4'),
 Clade(branch_length=72.03945324, name='t5'),
 Clade(branch_length=24.52738835, name='t6'),
 Clade(branch_length=8.200710303, name='t7'),
 Clade(branch_length=8.164346021, name='t8'),
 Clade(branch_length=55.88317411, name='t9'),
 Clade(branch_length=55.20569545, name='t10'),
 Clade(branch_length=81.32493379, name='t11'),
 Clade(branch_length=9.876600217, name='t12'),
 Clade(branch_length=9.0138726, name='t13'),
 Clade(branch_length=14.58361624, name='t14'),
 Clade(branch_length=53.90269216, name='t15'),
 Clade(branch_length=115.1695439, name='t16'),
 Clade(branch_length=46.60402976, name='t17'),
 Clade(branch_length=45.41464108, name='t18'),
 Clade(branch_length=58.53418386, name='t19'),
 Clade(branch_length=33.30585927, name='t20'),
 Clade(branch_length=33.17455168, name='t21'),
 Clade(branch_length=9.777849086, name='t22'),
 Clade(branch_length=9.220883541, name='t23'),
 Clade(branch_length=13.82950755, name='t24'),
 Clade(branch_length=37.21088317, name='t25'),
 Clade(branch_length=36.29725749, name='t26'),
 Clade(branch_length=95.65959859, name='t27'),
 Clade(branch_length=249.7336229, name='t28'),
 Clade(branch_length=51.70433703, name='t29'),
 Clade(branch_length=5.006060849, name='t30'),
 Clade(branch_length=4.936402344, name='t31'),
 Clade(branch_length=75.26662012, name='t32'),
 Clade(branch_length=5.813309351, name='t33'),
 Clade(branch_length=5.13642394, name='t34'),
 Clade(branch_length=29.41664922, name='t35'),
 Clade(branch_length=46.83971593, name='t36'),
 Clade(branch_length=36.61307198, name='t37'),
 Clade(branch_length=36.39586597, name='t38'),
 Clade(branch_length=42.13160476, name='t39'),
 Clade(branch_length=15.75226698, name='t40'),
 Clade(branch_length=15.61261264, name='t41'),
 Clade(branch_length=1.289628205, name='t42'),
 Clade(branch_length=1.09493075, name='t43'),
 Clade(branch_length=61.03365566, name='t44'),
 Clade(branch_length=59.68617227, name='t45'),
 Clade(branch_length=28.79180285, name='t46'),
 Clade(branch_length=27.54833082, name='t47'),
 Clade(branch_length=13.78290449, name='t48'),
 Clade(branch_length=12.96215908, name='t49'),
 Clade(branch_length=3.939738813, name='t50'),
 Clade(branch_length=2.821911699, name='t51'),
 Clade(branch_length=38.28066226, name='t52'),
 Clade(branch_length=55.14172672, name='t53'),
 Clade(branch_length=46.51816875, name='t54'),
 Clade(branch_length=44.45062912, name='t55'),
 Clade(branch_length=38.20072439, name='t56'),
 Clade(branch_length=20.78062896, name='t57'),
 Clade(branch_length=20.76054516, name='t58'),
 Clade(branch_length=31.36248841, name='t59'),
 Clade(branch_length=28.64030657, name='t60'),
 Clade(branch_length=28.58802601, name='t61'),
 Clade(branch_length=31.0128803, name='t62'),
 Clade(branch_length=30.57939316, name='t63'),
 Clade(branch_length=48.48085609, name='t64'),
 Clade(branch_length=23.99137963, name='t65'),
 Clade(branch_length=22.94765373, name='t66'),
 Clade(branch_length=56.9869927, name='t67'),
 Clade(branch_length=54.1205658, name='t68'),
 Clade(branch_length=5.414493369, name='t69'),
 Clade(branch_length=4.784105514, name='t70'),
 Clade(branch_length=4.607163957, name='t71'),
 Clade(branch_length=13.05675177, name='t72'),
 Clade(branch_length=0.464911443, name='t73'),
 Clade(branch_length=0.02503098068, name='t74'),
 Clade(branch_length=3.184212648, name='t75'),
 Clade(branch_length=43.44011173, name='t76'),
 Clade(branch_length=27.26108832, name='t77'),
 Clade(branch_length=26.83983081, name='t78'),
 Clade(branch_length=38.60443704, name='t79'),
 Clade(branch_length=38.34696568, name='t80'),
 Clade(branch_length=115.0666402, name='t81'),
 Clade(branch_length=114.5463357, name='t82'),
 Clade(branch_length=75.38087545, name='t83'),
 Clade(branch_length=74.12948115, name='t84'),
 Clade(branch_length=46.56071837, name='t85'),
 Clade(branch_length=46.28274245, name='t86'),
 Clade(branch_length=62.2711137, name='t87'),
 Clade(branch_length=43.61453378, name='t88'),
 Clade(branch_length=43.61004904, name='t89'),
 Clade(branch_length=38.02855111, name='t90'),
 Clade(branch_length=37.63886174, name='t91'),
 Clade(branch_length=63.21307195, name='t92'),
 Clade(branch_length=11.49891061, name='t93'),
 Clade(branch_length=11.3677606, name='t94'),
 Clade(branch_length=11.93107304, name='t95'),
 Clade(branch_length=4.626101633, name='t96'),
 Clade(branch_length=4.615104995, name='t97'),
 Clade(branch_length=53.83920579, name='t98'),
 Clade(branch_length=24.25271397, name='t99'),
 Clade(branch_length=24.08429857, name='t100'),
 Clade(branch_length=12.83102102, name='t101'),
 Clade(branch_length=12.5090022, name='t102'),
 Clade(branch_length=11.8367177, name='t103'),
 Clade(branch_length=11.05793691, name='t104'),
 Clade(branch_length=33.76110887, name='t105'),
 Clade(branch_length=11.89124138, name='t106'),
 Clade(branch_length=11.74834602, name='t107'),
 Clade(branch_length=18.95484656, name='t108'),
 Clade(branch_length=13.66845066, name='t109'),
 Clade(branch_length=13.42775698, name='t110'),
 Clade(branch_length=8.937486367, name='t111'),
 Clade(branch_length=7.830085059, name='t112'),
 Clade(branch_length=82.52951569, name='t113'),
 Clade(branch_length=4.817223241, name='t114'),
 Clade(branch_length=4.299202952, name='t115'),
 Clade(branch_length=14.53520568, name='t116'),
 Clade(branch_length=14.22710676, name='t117'),
 Clade(branch_length=16.48381994, name='t118'),
 Clade(branch_length=24.49914135, name='t119'),
 Clade(branch_length=24.42420434, name='t120'),
 Clade(branch_length=42.89815647, name='t121'),
 Clade(branch_length=41.3437511, name='t122')]

In [ ]:
            # Read alignment and format as BEAST-compatible XML block
            alignment = AlignIO.read(aln_path, "fasta")
            output_align = io.StringIO()
            for record in alignment:
                #output_align.write(f'\n\t\t\t\t\t<sequence spec="Sequence" taxon="{record.id}" value="{str(record.seq)}" />')
                output_align.write(f'\n\t<sequence><taxon idref="{record.id}"/>{str(record.seq)}</sequence>')
            # Set parameters not in the config file
            pars["taxa"] = output_align.getvalue()

In [ ]:
def pars_dates(tree, pars):
    """
    Add dates to the tree in the BEAST XML parameters.
    """
    output_dates = StringIO()

    tree_ = Phylo.read(StringIO(tree), "newick")
    leaves = tree_.get_terminals()

    # Compute distances from root to each leaf (sampling height)
    heights = np.array([tree_.distance(leaf) for leaf in leaves])
    treetimes = np.max(heights) - heights
    leaf_names = [leaf.name for leaf in leaves]

    for i, leaf_name in enumerate(leaf_names):
        output_dates.write(f'\n\t<taxon id = "{leaf_name}"> <date value="{treetimes[i]}" direction="backwards" units="years"/> </taxon>')

    pars["dates"] = output_dates.getvalue()

In [72]:
tree_line = "(((((((t123:85.51169686,t124:85.20077156):7.343365349,(t125:29.40221713,t126:29.20843118):63.11290296):289.956407,(t127:244.644568,(((t128:26.18635088,t129:26.14262086):13.84757867,((t130:21.42206384,t131:19.96622763):17.34847746,t132:36.97792539):1.058985511):9.845577978,((t133:24.31275061,((t134:15.27725582,t135:14.6616526):6.5619838,t136:21.20150853):2.267177142):21.00649058,t137:43.9680417):2.524411378):194.6177663):137.1583196):403.4837819,((t138:12.81287944,t139:11.90913365):43.38167875,(t140:6.631340953,t141:6.186669348):48.3076185):724.9651857):828.4140678,(t142:282.3984372,((t143:24.8067227,t144:24.01293535):181.7886839,(t145:1.665177037,t146:1.233016773):204.0694754):75.77391343):1324.583421):1784.875949,(((((t147:5.075415489,t148:4.331392641):5.0400927,t149:9.287065444):69.71574544,(t150:25.77983416,(t151:23.14353761,t152:23.01059492):2.625521291):51.67712957):38.4252127,(t153:39.32858169,t154:38.86890371):76.08494234):450.3432882,((((((t155:6.501519402,(t156:5.112483802,t157:4.798736082):1.178995211):11.67523512,t158:16.76180654):4.574980565,(t159:11.51923451,t160:10.72834069):9.105124658):31.0904289,t161:50.77555151):2.85343334,(t162:18.15745443,t163:17.95611744):34.94200278):283.8208794,(((((t164:18.00394497,(t165:6.370289088,t166:5.935099884):11.47095318):99.62947934,((t167:20.07805183,t168:19.66252073):31.89128786,(t169:50.2751031,t170:49.96946908):1.127506835):64.8118296):105.4726258,((((t171:20.7640469,t172:20.55289959):26.83457463,(t173:3.132601653,t174:3.081646737):43.68631935):37.09070349,((t175:10.60626825,(t176:8.38900566,t177:8.221200168):2.215046601):66.37127935,t178:75.9061895):5.801951552):84.9812876,((((t179:12.93423768,t180:11.948838):13.82790165,(t181:19.73975543,t182:18.66957601):5.456336538):34.62004259,(t183:50.89858956,(t184:19.70217632,t185:19.66577465):30.59006162):7.502177309):37.79863801,((t186:10.86301823,t187:10.85438142):9.659181448,t188:20.13616126):74.58712515):67.36717053):51.42396909):53.64542889,(t189:246.7057591,((((t190:35.5785022,t191:35.23160107):13.43229019,(t192:24.6913429,t193:23.47929574):23.21268286):9.600603416,((((t1:97.06484683,(((t2:23.71789582,t3:23.66248825):55.6411441,(t4:74.61738058,(t5:72.03945324,((t6:24.52738835,(t7:8.200710303,t8:8.164346021):16.16725409):42.08599551,(t9:55.88317411,t10:55.20569545):9.905839193):5.0109684):2.506353574):2.887407175):7.039082311,(t11:81.32493379,(((t12:9.876600217,t13:9.0138726):5.733114758,t14:14.58361624):39.51343857,t15:53.90269216):26.00434397):0.8948687282):10.62741294):23.77375871,t16:115.1695439):6.809147444,(((t17:46.60402976,t18:45.41464108):13.23009948,t19:58.53418386):20.24717966,(t20:33.30585927,t21:33.17455168):44.51403098):41.49041021):4.840497746,((((t22:9.777849086,t23:9.220883541):4.966160145,t24:13.82950755):25.56178769,(t25:37.21088317,t26:36.29725749):1.696076883):58.02135063,t27:95.65959859):25.63917925):22.71679972):105.9811786,t28:249.7336229):81.85274293):19.98247445):14.96787122,((((t29:51.70433703,(t30:5.006060849,t31:4.936402344):46.6527271):23.98630916,t32:75.26662012):146.3987774,((((t33:5.813309351,t34:5.13642394):24.36889788,t35:29.41664922):44.99042741,(t36:46.83971593,(t37:36.61307198,t38:36.39586597):9.784806596):27.15995883):50.95413607,(((t39:42.13160476,((t40:15.75226698,t41:15.61261264):4.757455761,(t42:1.289628205,t43:1.09493075):18.35219996):21.40773715):78.71378972,(t44:61.03365566,t45:59.68617227):58.01999681):3.191992108,(t46:28.79180285,t47:27.54833082):91.03818126):0.09149099181):95.43945306):132.9479019,(((((((((t48:13.78290449,t49:12.96215908):25.22755982,(t50:3.939738813,t51:2.821911699):33.87850762):1.586335351,t52:38.28066226):18.08921491,t53:55.14172672):9.033134053,(t54:46.51816875,t55:44.45062912):17.47675668):2.602648221,((t56:38.20072439,((t57:20.78062896,t58:20.76054516):10.99659374,t59:31.36248841):5.722765268):19.53237375,(t60:28.64030657,t61:28.58802601):25.44568922):6.368856928):1.866470108,((t62:31.0128803,t63:30.57939316):19.86012033,t64:48.48085609):10.25804289):200.4307214,(t65:23.99137963,t66:22.94765373):235.1381662):2.885629019,(((t67:56.9869927,t68:54.1205658):44.41857206,((t69:5.414493369,(t70:4.784105514,t71:4.607163957):0.3073624622):51.42416671,(t72:13.05675177,((t73:0.464911443,t74:0.02503098068):7.39178421,t75:3.184212648):4.491543783):43.24784729):41.64969963):67.37704604,(((t76:43.44011173,(t77:27.26108832,t78:26.83983081):15.01313293):1.955716795,(t79:38.60443704,t80:38.34696568):3.653345889):88.08571429,(t81:115.0666402,t82:114.5463357):10.33256969):26.27589871):91.11690811):71.31895093):11.16830144):44.81597559):224.6695928):2821.700378):354.9380153,((((t83:75.38087545,t84:74.12948115):141.9932271,(((t85:46.56071837,t86:46.28274245):16.65469849,t87:62.2711137):24.34510691,((t88:43.61453378,t89:43.61004904):41.81020001,((t90:38.02855111,t91:37.63886174):25.6182063,t92:63.21307195):21.44263371):1.001441999):128.294883):180.1642534,((((t93:11.49891061,t94:11.3677606):61.49801816,((t95:11.93107304,(t96:4.626101633,t97:4.615104995):6.647926307):42.69934083,t98:53.83920579):17.92581868):67.56357924,(((t99:24.25271397,t100:24.08429857):28.3772211,(((t101:12.83102102,t102:12.5090022):22.17070991,(t103:11.8367177,t104:11.05793691):22.52271151):0.5620867758,t105:33.76110887):15.17674998):1.054430019,((t106:11.89124138,t107:11.74834602):8.169461656,t108:18.95484656):29.89984851):85.12034301):47.66548495,(t109:13.66845066,t110:13.42775698):167.9487691):205.8565257):232.0299868,(((t111:8.937486367,t112:7.830085059):75.23544991,t113:82.52951569):455.1592802,((((t114:4.817223241,t115:4.299202952):38.79873362,((t116:14.53520568,t117:14.22710676):2.514260427,t118:16.48381994):25.79467207):3.144691536,(t119:24.49914135,t120:24.42420434):20.80350828):49.25106912,(t121:42.89815647,t122:41.3437511):51.36787791):441.3089666):79.83073337):3141.157481)"
tree = Phylo.read(StringIO(tree_line), "newick")

leaves = tree.get_terminals()

# Compute distances from root to each leaf (sampling height)
heights = np.array([tree.distance(leaf) for leaf in leaves])
treetimes = max(heights) - heights
leaf_names = [leaf.name for leaf in leaves]

leaf_names = [leaf.name for leaf in leaves]
sampling_df = pd.DataFrame({
    'name': leaf_names,
    'sampling_time': treetimes
})

sampling_df.to_csv("data/sampling_times.csv", index=False, sep='\t')

In [ ]:
# Map names to sampling times
sampling_times = {leaf.name: time for leaf, time in zip(leaves, treetimes)}

In [ ]:

df

     name  sampling_time
0    t123      69.589996
1    t124      69.900921
2    t125      69.929938
3    t126      70.123724
4    t127      70.598578
..    ...            ...
188  t118      67.141846
189  t119      67.262380
190  t120      67.337317
191  t121      67.550064
192  t122      69.104469

[193 rows x 2 columns]

In [ ]:
treetimes = max(heights) - heights

sampling_times = {leaf.name: time for leaf, time in zip(leaves, treetimes)}
pd.DataFrame.from_dict(sampling_times, orient='index', columns=['sampling_time']).sort_values('sampling_time').reset_index()

    index  sampling_time
0      t1       0.000000
1      t2       0.039312
2      t3       0.094719
3      t4       1.893564
4      t5       1.965138
..    ...            ...
188  t189      96.333213
189  t190      96.593655
190  t191      96.940556
191  t192      97.700421
192  t193      98.912468

[193 rows x 2 columns]

In [38]:

tree_text = "(((((((t123:85.51169686,t124:85.20077156):7.343365349,(t125:29.40221713,t126:29.20843118):63.11290296):289.956407,(t127:244.644568,(((t128:26.18635088,t129:26.14262086):13.84757867,((t130:21.42206384,t131:19.96622763):17.34847746,t132:36.97792539):1.058985511):9.845577978,((t133:24.31275061,((t134:15.27725582,t135:14.6616526):6.5619838,t136:21.20150853):2.267177142):21.00649058,t137:43.9680417):2.524411378):194.6177663):137.1583196):403.4837819,((t138:12.81287944,t139:11.90913365):43.38167875,(t140:6.631340953,t141:6.186669348):48.3076185):724.9651857):828.4140678,(t142:282.3984372,((t143:24.8067227,t144:24.01293535):181.7886839,(t145:1.665177037,t146:1.233016773):204.0694754):75.77391343):1324.583421):1784.875949,(((((t147:5.075415489,t148:4.331392641):5.0400927,t149:9.287065444):69.71574544,(t150:25.77983416,(t151:23.14353761,t152:23.01059492):2.625521291):51.67712957):38.4252127,(t153:39.32858169,t154:38.86890371):76.08494234):450.3432882,((((((t155:6.501519402,(t156:5.112483802,t157:4.798736082):1.178995211):11.67523512,t158:16.76180654):4.574980565,(t159:11.51923451,t160:10.72834069):9.105124658):31.0904289,t161:50.77555151):2.85343334,(t162:18.15745443,t163:17.95611744):34.94200278):283.8208794,(((((t164:18.00394497,(t165:6.370289088,t166:5.935099884):11.47095318):99.62947934,((t167:20.07805183,t168:19.66252073):31.89128786,(t169:50.2751031,t170:49.96946908):1.127506835):64.8118296):105.4726258,((((t171:20.7640469,t172:20.55289959):26.83457463,(t173:3.132601653,t174:3.081646737):43.68631935):37.09070349,((t175:10.60626825,(t176:8.38900566,t177:8.221200168):2.215046601):66.37127935,t178:75.9061895):5.801951552):84.9812876,((((t179:12.93423768,t180:11.948838):13.82790165,(t181:19.73975543,t182:18.66957601):5.456336538):34.62004259,(t183:50.89858956,(t184:19.70217632,t185:19.66577465):30.59006162):7.502177309):37.79863801,((t186:10.86301823,t187:10.85438142):9.659181448,t188:20.13616126):74.58712515):67.36717053):51.42396909):53.64542889,(t189:246.7057591,((((t190:35.5785022,t191:35.23160107):13.43229019,(t192:24.6913429,t193:23.47929574):23.21268286):9.600603416,((((t1:97.06484683,(((t2:23.71789582,t3:23.66248825):55.6411441,(t4:74.61738058,(t5:72.03945324,((t6:24.52738835,(t7:8.200710303,t8:8.164346021):16.16725409):42.08599551,(t9:55.88317411,t10:55.20569545):9.905839193):5.0109684):2.506353574):2.887407175):7.039082311,(t11:81.32493379,(((t12:9.876600217,t13:9.0138726):5.733114758,t14:14.58361624):39.51343857,t15:53.90269216):26.00434397):0.8948687282):10.62741294):23.77375871,t16:115.1695439):6.809147444,(((t17:46.60402976,t18:45.41464108):13.23009948,t19:58.53418386):20.24717966,(t20:33.30585927,t21:33.17455168):44.51403098):41.49041021):4.840497746,((((t22:9.777849086,t23:9.220883541):4.966160145,t24:13.82950755):25.56178769,(t25:37.21088317,t26:36.29725749):1.696076883):58.02135063,t27:95.65959859):25.63917925):22.71679972):105.9811786,t28:249.7336229):81.85274293):19.98247445):14.96787122,((((t29:51.70433703,(t30:5.006060849,t31:4.936402344):46.6527271):23.98630916,t32:75.26662012):146.3987774,((((t33:5.813309351,t34:5.13642394):24.36889788,t35:29.41664922):44.99042741,(t36:46.83971593,(t37:36.61307198,t38:36.39586597):9.784806596):27.15995883):50.95413607,(((t39:42.13160476,((t40:15.75226698,t41:15.61261264):4.757455761,(t42:1.289628205,t43:1.09493075):18.35219996):21.40773715):78.71378972,(t44:61.03365566,t45:59.68617227):58.01999681):3.191992108,(t46:28.79180285,t47:27.54833082):91.03818126):0.09149099181):95.43945306):132.9479019,(((((((((t48:13.78290449,t49:12.96215908):25.22755982,(t50:3.939738813,t51:2.821911699):33.87850762):1.586335351,t52:38.28066226):18.08921491,t53:55.14172672):9.033134053,(t54:46.51816875,t55:44.45062912):17.47675668):2.602648221,((t56:38.20072439,((t57:20.78062896,t58:20.76054516):10.99659374,t59:31.36248841):5.722765268):19.53237375,(t60:28.64030657,t61:28.58802601):25.44568922):6.368856928):1.866470108,((t62:31.0128803,t63:30.57939316):19.86012033,t64:48.48085609):10.25804289):200.4307214,(t65:23.99137963,t66:22.94765373):235.1381662):2.885629019,(((t67:56.9869927,t68:54.1205658):44.41857206,((t69:5.414493369,(t70:4.784105514,t71:4.607163957):0.3073624622):51.42416671,(t72:13.05675177,((t73:0.464911443,t74:0.02503098068):7.39178421,t75:3.184212648):4.491543783):43.24784729):41.64969963):67.37704604,(((t76:43.44011173,(t77:27.26108832,t78:26.83983081):15.01313293):1.955716795,(t79:38.60443704,t80:38.34696568):3.653345889):88.08571429,(t81:115.0666402,t82:114.5463357):10.33256969):26.27589871):91.11690811):71.31895093):11.16830144):44.81597559):224.6695928):2821.700378):354.9380153,((((t83:75.38087545,t84:74.12948115):141.9932271,(((t85:46.56071837,t86:46.28274245):16.65469849,t87:62.2711137):24.34510691,((t88:43.61453378,t89:43.61004904):41.81020001,((t90:38.02855111,t91:37.63886174):25.6182063,t92:63.21307195):21.44263371):1.001441999):128.294883):180.1642534,((((t93:11.49891061,t94:11.3677606):61.49801816,((t95:11.93107304,(t96:4.626101633,t97:4.615104995):6.647926307):42.69934083,t98:53.83920579):17.92581868):67.56357924,(((t99:24.25271397,t100:24.08429857):28.3772211,(((t101:12.83102102,t102:12.5090022):22.17070991,(t103:11.8367177,t104:11.05793691):22.52271151):0.5620867758,t105:33.76110887):15.17674998):1.054430019,((t106:11.89124138,t107:11.74834602):8.169461656,t108:18.95484656):29.89984851):85.12034301):47.66548495,(t109:13.66845066,t110:13.42775698):167.9487691):205.8565257):232.0299868,(((t111:8.937486367,t112:7.830085059):75.23544991,t113:82.52951569):455.1592802,((((t114:4.817223241,t115:4.299202952):38.79873362,((t116:14.53520568,t117:14.22710676):2.514260427,t118:16.48381994):25.79467207):3.144691536,(t119:24.49914135,t120:24.42420434):20.80350828):49.25106912,(t121:42.89815647,t122:41.3437511):51.36787791):441.3089666):79.83073337):3141.157481)"
tree = Nexus.Trees.Tree(tree_text)

In [39]:
len(tree.get_terminals())

193

In [40]:
# Sampling times from tree
#tree    = Nexus.Trees.Tree(newicktree)
forwards = False
leaves  = tree.get_terminals()
heights = np.zeros(len(leaves))	
for i in range(0,len(leaves)):
    heights[i] = tree.sum_branchlength(node=leaves[i])

# Forwards or backwards
if (forwards == True):
    treetimes = heights
else:
    treetimes = max(heights) - heights

In [42]:
leaves

[7,
 8,
 10,
 11,
 13,
 17,
 18,
 21,
 22,
 23,
 26,
 29,
 30,
 31,
 32,
 35,
 36,
 38,
 39,
 41,
 44,
 45,
 47,
 48,
 54,
 55,
 56,
 58,
 60,
 61,
 63,
 64,
 71,
 73,
 74,
 75,
 77,
 78,
 79,
 81,
 82,
 88,
 90,
 91,
 94,
 95,
 97,
 98,
 103,
 104,
 106,
 107,
 110,
 112,
 113,
 114,
 119,
 120,
 122,
 123,
 125,
 127,
 128,
 131,
 132,
 133,
 135,
 140,
 141,
 143,
 144,
 149,
 153,
 154,
 156,
 158,
 161,
 163,
 164,
 166,
 167,
 169,
 173,
 174,
 175,
 176,
 177,
 181,
 182,
 183,
 185,
 186,
 191,
 192,
 193,
 195,
 196,
 197,
 198,
 203,
 205,
 206,
 207,
 212,
 213,
 214,
 216,
 218,
 219,
 223,
 226,
 227,
 229,
 230,
 232,
 233,
 235,
 236,
 246,
 247,
 249,
 250,
 251,
 252,
 254,
 255,
 258,
 261,
 262,
 263,
 265,
 266,
 269,
 270,
 271,
 273,
 274,
 278,
 279,
 282,
 284,
 285,
 287,
 290,
 291,
 292,
 296,
 298,
 299,
 301,
 302,
 304,
 305,
 310,
 311,
 315,
 316,
 317,
 320,
 321,
 324,
 325,
 326,
 331,
 332,
 335,
 337,
 338,
 339,
 343,
 344,
 348,
 349,
 351,
 352,
 353,
 356,
 357,
 358,
 360,
 361,
 365,
 366,
 367,
 372,
 373,
 376,
 377,
 378,
 380,
 381,
 383,
 384]

In [41]:
treetimes

array([6.95899961e+01, 6.99009214e+01, 6.99299383e+01, 7.01237242e+01,
       7.05985777e+01, 7.07458719e+01, 7.07896019e+01, 7.09502747e+01,
       7.24061109e+01, 7.27428906e+01, 7.27817269e+01, 7.29880607e+01,
       7.36036639e+01, 7.36257918e+01, 7.41329264e+01, 7.47255034e+01,
       7.56292491e+01, 7.59811021e+01, 7.64257737e+01, 7.73174568e+01,
       7.73465740e+01, 7.81403614e+01, 7.82073282e+01, 7.86394884e+01,
       7.88751315e+01, 7.96191544e+01, 7.97035743e+01, 8.12494214e+01,
       8.12601967e+01, 8.13931394e+01, 8.17180738e+01, 8.21777518e+01,
       8.22888165e+01, 8.24988569e+01, 8.28126046e+01, 8.37037645e+01,
       8.44161924e+01, 8.52070863e+01, 8.53554290e+01, 8.58849566e+01,
       8.60862936e+01, 8.62699674e+01, 8.64326701e+01, 8.68678593e+01,
       8.71222224e+01, 8.75377536e+01, 8.76889522e+01, 8.79945862e+01,
       8.82814358e+01, 8.84925831e+01, 8.90611364e+01, 8.91120913e+01,
       9.01912617e+01, 9.01934777e+01, 9.03612832e+01, 9.12626198e+01,
       9.14040580e+01, 9.23894577e+01, 9.29701054e+01, 9.40402848e+01,
       9.43854730e+01, 9.49918247e+01, 9.50282263e+01, 9.54755531e+01,
       9.54841899e+01, 9.58615915e+01, 9.63332129e+01, 9.65936546e+01,
       9.69405558e+01, 9.77004213e+01, 9.89124684e+01, 0.00000000e+00,
       3.93116590e-02, 9.47192290e-02, 1.89356382e+00, 1.96513759e+00,
       2.38023857e+00, 2.53966253e+00, 2.57602681e+00, 3.20460913e+00,
       3.88208779e+00, 4.21763137e+00, 4.41506765e+00, 5.27779526e+00,
       5.44116638e+00, 5.63552903e+00, 5.66906164e+00, 6.07603387e+00,
       7.26542255e+00, 7.37597925e+00, 8.33745252e+00, 8.46876011e+00,
       8.52192393e+00, 9.07888947e+00, 9.43642561e+00, 9.92076080e+00,
       1.08343865e+01, 1.11894729e+01, 1.14526062e+01, 1.17836907e+01,
       1.18292398e+01, 1.18988983e+01, 1.22077168e+01, 1.23068905e+01,
       1.29837760e+01, 1.30724485e+01, 1.34798504e+01, 1.39216878e+01,
       1.41388938e+01, 1.43047837e+01, 1.45189285e+01, 1.46585829e+01,
       1.53868231e+01, 1.55815206e+01, 1.60965257e+01, 1.74440091e+01,
       1.85121861e+01, 1.97556582e+01, 1.99974479e+01, 2.08181933e+01,
       2.11896658e+01, 2.23074929e+01, 2.23135853e+01, 2.35417358e+01,
       2.37216711e+01, 2.57892107e+01, 2.62172897e+01, 2.69180261e+01,
       2.69381099e+01, 2.73327604e+01, 2.98643920e+01, 2.99166726e+01,
       3.10546713e+01, 3.14881585e+01, 3.34468159e+01, 3.34868904e+01,
       3.45306163e+01, 3.56025464e+01, 3.84689733e+01, 3.85197514e+01,
       3.88427768e+01, 3.90197184e+01, 3.90538124e+01, 3.97623248e+01,
       4.02022052e+01, 4.44348078e+01, 4.46277156e+01, 4.57936061e+01,
       4.62148636e+01, 4.77657612e+01, 4.80232326e+01, 5.27100486e+01,
       5.32303531e+01, 5.33874556e+01, 5.46388499e+01, 5.49061514e+01,
       5.51841273e+01, 5.58504545e+01, 5.60404994e+01, 5.60449841e+01,
       5.63758420e+01, 5.67655314e+01, 5.68095275e+01, 5.68432929e+01,
       5.69744429e+01, 5.72839891e+01, 5.79410342e+01, 5.79520308e+01,
       5.80751972e+01, 5.85990928e+01, 5.87675082e+01, 6.04884602e+01,
       6.08104790e+01, 6.11307619e+01, 6.19095427e+01, 6.22911690e+01,
       6.23229063e+01, 6.24658017e+01, 6.34287628e+01, 6.34520661e+01,
       6.36927598e+01, 6.37928485e+01, 6.49002498e+01, 6.54362691e+01,
       6.58043809e+01, 6.63224011e+01, 6.65761995e+01, 6.68842985e+01,
       6.71418457e+01, 6.72623796e+01, 6.73373166e+01, 6.75500640e+01,
       6.91044694e+01])